In [2]:
import numpy as np
a=[[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]
y=np.array(a)
print(y)
print(y.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [8]:
%timeit [j**4 for j in range(1,9)]


861 ns ± 15 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
l=[]
for i in range(1,5):
    in_1=int(input("enter:"))
    l.append(in_1)

print(np.array(l))
print(type(l))


enter: 534
enter: 22
enter: 552
enter: 222


[534  22 552 222]
<class 'list'>


In [15]:
print(np.array(l))

['25' '45' '34' '45']


In [24]:
arn= np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [25]:
zeros=np.zeros((4,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
arrone=np.ones((4,5))
print(arrone)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
arri=np.eye(4)
print(arri)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
kesh=np.linspace(0,16,num=5)
print(kesh)


[ 0.  4.  8. 12. 16.]


In [16]:
var=np.array([[[1,2,3,4]]])
print(var.ndim)
var2=np.array([[[1,2,2,5],[1,2,3,4]]],ndmin=5)
print(var2)

3
[[[[[1 2 2 5]
    [1 2 3 4]]]]]


#speatial type of array

In [19]:
var=np.zeros(3)
va=np.empty(4)
vat=np.ones(4)
x=np.eye(5)
print(x)
print(var,va,vat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0. 0. 0.] [1. 1. 1. 1.] [1. 1. 1. 1.]


In [33]:
var=np.linspace(1,12,num=6)
print(var)

[ 1.   3.2  5.4  7.6  9.8 12. ]


In [49]:
x=np.random.rand(5)
print(x)
y=np.random.randn(5)
print(y)
z=np.random.ranf(5)
print(z)
w=np.random.randint(0,454,45)
print(w)

[0.38336104 0.32997832 0.8280411  0.09878266 0.22440877]
[ 0.30504461  1.78524723 -0.55656746  0.13347833 -0.48605787]
[0.93660484 0.95062994 0.20439256 0.74907544 0.19562463]
[106 338 110  44 215 106 412 278 227 359 298 421 312 446 252 280 247  52
 137 409  56 255  79 322 102 311 155 170 408 419 327  31  41 325 293 167
 228 412 201 196  58 269  44  40 415]


In [57]:
x=np.array([12.25,453,454,5454])
print("datatype",x.dtype)
y=np.int64(x)
print(y)
v=x.astype(int)
print(v)

datatype float64
[  12  453  454 5454]
[  12  453  454 5454]


In [67]:
b=np.array([1,23,4,5],ndmin=10)
print(b)
one=b.reshape(-1)
print(one)

[[[[[[[[[[ 1 23  4  5]]]]]]]]]]
[ 1 23  4  5]


In [75]:
bc=np.array([1,23,4,5,1,23,44,5])
print(bc)
print(np.min(bc))
print(np.max(bc))
print(np.argmin(bc))
print(np.sqrt(bc))
print(np.sin(bc))


[ 1 23  4  5  1 23 44  5]
1
44
0
[1.         4.79583152 2.         2.23606798 1.         4.79583152
 6.63324958 2.23606798]
[ 0.84147098 -0.8462204  -0.7568025  -0.95892427  0.84147098 -0.8462204
  0.01770193 -0.95892427]


In [77]:
fh=np.array([[1,23,4,5,1,23,44,5],[1,23,4,5,1,23,44,5]])
print(fh[0,2])
print(fh[1,5])
print(fh[0,2])


4
23
4


In [81]:
fh=np.array([[1,23,4,5,1,23,44,5],[1,23,4,5,1,23,44,5]])
c=fh[0,5:7]
d=fh[0,2:7:2]
print(d)
print(c)

[ 4  1 44]
[23 44]
